.TH "beet-burger" 7 "February 17, 2018" "Recipes" "Beet Burger"
.SH NAME
Beet Burger - This is a recipe for a delicious burger that I discovered
completely on accident.

.SH RECIPE

pinch	Cumin

pinch	Chili Powder

pinch	Oregano

pinch	Cinnamon

1tbsp	Hot sauce of your choice (I use Founder's Blis Sauce)

1/4lb	Ground beef

1/4tsp	Minced Garlic

2tbsp	Horseradish Mustard

1tbsp	Balsamic Vinegar

Some	     Pickled Beets (3 or 4 slices, chef's choice)

2	     Burger buns

1slice	Swiss Cheese

Some	     Chopped Kale (chef's choice)

1/2c	     Mayonnaise

1/2c	     Greek Yogurt

Some	     Olive Oil

.SH INSTRUCTIONS

Preheat the pan with the Olive Oil on medium heat. Pound the patty with the
minced garlic so that the garlic is evenly distributed in the meat. Place in
the pan and season with the Chili Powder, Cumin, Cinnamon, Oregano, and Hot
Sauce, then cover. Squeeze with a spatula occasionally. Cook until medium rare.
Place the swiss cheese on the burger, then remove from the pan and allow to
cool slightly. Mix the Horseradish Mustard and Balsamic Vinegar in a separate
container until evenly smooth, then spread onto the bun. Layer on Kale and
burger, then place Pickled Beets and bun on top. All done! Recipe makes one
burger.
