.TH "skillet-greens" 7 "February 24, 2018" "Recipes" "Skillet Greens"
.SH NAME
Skillet Greens - A surprisingly good mix of common breakfast foods with some
healthy kale and spring mix

.SH RECIPE

1	    Clove Garlic

1/2	    Small Potato (1/2c total, sliced about the size of a dime)

Some	    Mixed greens (I used Kale and spring mix--about half the bowl)

Some	    Oil of your choice (I used Canola oil)

1/4	    Onion (About 1/4-1/3c total), thinly sliced

2	    Eggs

Some	    Parmesan Cheese

Some	    Hot Sauce (I used Founder's Blis)

.SH INSTRUCTIONS

Begin frying the potato and onion in a skillet with the oil. The oil should be
enough to lightly cover the bottom of the skillet. Potatoes absorb a lot of
oil when frying, so don't be afraid to add more if necessary. Mince the
garlic (coarsely) and add to the skillet when it feels right. It's okay if the
garlic gets crispy, it will only add more to the dish, but the potatoes need to
be fully cooked. Fill the bowl about halfway with the salad greens. When the
skillet mixture is finished, layer it on top of the salad greens. Fry the eggs
(Low heat, covered) until the yolk is safely encapsulated but still liquid on
the inside, and place on the top of the bowl. Sprinkle some Parmesan cheese and
hot sauce on top. Enjoy!
