.TH "chicken-salad" 7 "January 23, 2018" "Recipes" "Chicken Salad"
.SH NAME
Chicken Salad - This is a recipe for a plain and simple chicken salad.

.SH RECIPE

1/2c	     Mayonnaise

1/2c	     Greek Yogurt

1tbsp	Dijon Mustard

1tbsp	Fresh Lemon Juice OR one finely chopped lemon wedge

4 - 5c	Chopped Cooked Chicken (About 5 breasts)

3/4c	     Chopped Green Onions

1,1/4c	Diced Celery

1/4c	     Cranberries

1tbsp	Chopped Fresh Dill

1tbsp	Chopped Fresh Flat-Leaf Parsley

1tsp	     Kosher salt

1tsp	     Ground Black Pepper

.SH INSTRUCTIONS

Whisk together the mayonnaise, yogurt, mustard and lemon juice in a large bowl.
Stir in the remaining ingredients until well blended. Serve with crunchy,
buttery crackers or on whole grain bread with lettuce and tomato.
