.TH "yakisoba" 7 "February 18, 2018" "Recipes" "Yakisoba"
.SH NAME
Yakisoba - A delicious vegetarian japanese dish made from stir fried vegetables
and soba noodles.

.SH RECIPE

1/2tsp	Sesame Oil

1tbsp	Olive Oil

2tbsp	Chile Paste

2	     Chopped Garlic Cloves

1.5lb	Seitan

1/2c	     Low Sodium Soy Sauce

1	     Onion, Julienned

1/2	     Head Medium Cabbage, Coarsely Chopped

2	     Carrots, Julienned

8oz	     Soba Noodles, Cooked, Drained, and Scrubbed.

.SH INSTRUCTIONS

Begin boiling the water for the soba noodles. When the water is ready, cook the
soba noodles according to the instructions on the package with a pinch of salt.
When the Soba is finished, drain and rinse with cool water, and scrub
thoroughly to remove surface glutens from the buckwheat. Preheat a cast iron
skillet with the Olive and Sesame Oils, and when it is up to temperature, add
the Chile Paste and stir fry for 30 seconds. Then add the Garlic and stir fry
for an additional 30 seconds. Add the Seitan and 1/4c of the Soy Sauce, and
stir fry until the Seitan is lightly prepared. Combine the Cabbage, Onion, and
Carrots. Stir fry until the Cabbage is beginning to wilt. Finally, add the
remainder of the Soy Sauce and stir fry until the cabbage and onions are
thoroughly cooked. Remove the mixture from heat, blend with the noodles, and
serve.
